<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
  <channel>
    <title>那些年遇过的坑 - 分类   夏洛魂的个人博客</title>
    <link>https://XiaLuoHun.top/categories/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/</link>
    <description>那些年遇过的坑 - 分类 | 夏洛魂的个人博客</description>
    <generator>Hugo -- gohugo.io</generator><language>zh-CN</language><lastBuildDate>Tue, 20 Aug 2024 00:00:00 &#43;0000</lastBuildDate><atom:link href="https://XiaLuoHun.top/categories/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/" rel="self" type="application/rss+xml" /><item>
  <title>AptUpdate失败</title>
  <link>https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/aptupdate%E5%A4%B1%E8%B4%A5/</link>
  <pubDate>Tue, 20 Aug 2024 00:00:00 &#43;0000</pubDate>
  <author>夏洛魂</author>
  <guid>https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/aptupdate%E5%A4%B1%E8%B4%A5/</guid>
  <description><![CDATA[<div class="featured-image"><img loading="eager" src="https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/aptupdate%E5%A4%B1%E8%B4%A5/images/%E5%A4%B1%E8%B4%A5.png" alt="AptUpdate失败" title="AptUpdate失败" referrerpolicy="no-referrer"/></div>在Linux下使用apt update出现下述问题: 可依次使用下述命令解决: 1 2 3 4 5 echo &#34;deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse&#34; | tee /etc/apt/sources.list apt update -o Acquire::AllowInsecureRepositories=true -o Acquire::AllowDowngradeToInsecureRepositories=true apt install gnupg gnupg2 gnupg1 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys XXXXXX]]></description>
</item>
<item>
  <title>Python之FileNotFoundError</title>
  <link>https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/python%E4%B9%8Bfilenotfounderror/</link>
  <pubDate>Wed, 23 Mar 2022 00:00:00 &#43;0000</pubDate>
  <author>夏洛魂</author>
  <guid>https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/python%E4%B9%8Bfilenotfounderror/</guid>
  <description><![CDATA[<div class="featured-image"><img loading="eager" src="https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/python%E4%B9%8Bfilenotfounderror/images/%E9%94%99%E8%AF%AF.png" alt="Python之FileNotFoundError" title="Python之FileNotFoundError" referrerpolicy="no-referrer"/></div>现象 Python在Windows上处理长路径时,会出现下列错误. 解决方案 将HKEY_LOCAL_MACHINE\SYSTEM\Current]]></description>
</item>
<item>
  <title>VMware内存修改</title>
  <link>https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/vmware/</link>
  <pubDate>Tue, 14 Dec 2021 00:00:00 &#43;0000</pubDate>
  <author>夏洛魂</author>
  <guid>https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/vmware/</guid>
  <description><![CDATA[<div class="featured-image"><img loading="eager" src="https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/vmware/images/Vmware.png" alt="VMware内存修改" title="VMware内存修改" referrerpolicy="no-referrer"/></div>当前记录的VMware版本为16.2.1 build-18811642 注意 如果要对VMware中运行的系统进行内存修改,在Windwos下要调试的进程是vmware-v]]></description>
</item>
</channel>
</rss>
