<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>那些年遇过的坑 - 分类   夏洛魂的个人博客</title>
    <link>https://XiaLuoHun.top/categories/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/</link>
    <description>个人笔记本</description>
    <generator>Hugo 0.133.1 &amp; FixIt v0.3.11</generator>
    <language>zh-CN</language>
    <lastBuildDate>Tue, 20 Aug 2024 00:00:00 +0000</lastBuildDate>
    <atom:link href="https://XiaLuoHun.top/categories/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>AptUpdate失败</title>
      <link>https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/aptupdate%E5%A4%B1%E8%B4%A5/</link>
      <pubDate>Tue, 20 Aug 2024 00:00:00 +0000</pubDate>
      <guid>https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/aptupdate%E5%A4%B1%E8%B4%A5/</guid>
      <category domain="https://XiaLuoHun.top/categories/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/">那些年遇过的坑</category>
      <description>在Linux下使用apt update出现下述问题: 可依次使用下述命令解决: 1 2 3 4 5 echo &amp;#34;deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse&amp;#34; | tee /etc/apt/sources.list apt update -o Acquire::AllowInsecureRepositories=true -o Acquire::AllowDowngradeToInsecureRepositories=true apt install gnupg gnupg2 gnupg1 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys XXXXXX</description>
    </item>
    <item>
      <title>Python之FileNotFoundError</title>
      <link>https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/python%E4%B9%8Bfilenotfounderror/</link>
      <pubDate>Wed, 23 Mar 2022 00:00:00 +0000</pubDate>
      <guid>https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/python%E4%B9%8Bfilenotfounderror/</guid>
      <category domain="https://XiaLuoHun.top/categories/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/">那些年遇过的坑</category>
      <description>现象 Python在Windows上处理长路径时,会出现下列错误. 解决方案 将HKEY_LOCAL_MACHINE\SYSTEM\Current</description>
    </item>
    <item>
      <title>VMware内存修改</title>
      <link>https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/vmware/</link>
      <pubDate>Tue, 14 Dec 2021 00:00:00 +0000</pubDate>
      <guid>https://XiaLuoHun.top/posts/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/vmware/</guid>
      <category domain="https://XiaLuoHun.top/categories/%E9%82%A3%E4%BA%9B%E5%B9%B4%E9%81%87%E8%BF%87%E7%9A%84%E5%9D%91/">那些年遇过的坑</category>
      <description>当前记录的VMware版本为16.2.1 build-18811642 注意 如果要对VMware中运行的系统进行内存修改,在Windwos下要调试的进程是vmware-v</description>
    </item>
  </channel>
</rss>
